node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    try {
        stage('Test') {
            docker.image('qnib/pytest').inside {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        }
    } finally {
        junit 'test-reports/results.xml'
    }

    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?'
    }
    try {
        stage('Deploy to VPS') {
            steps {
                sshagent(['f954f3a3-6c6d-40c3-b5b6-8631010980ca']){
                sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@172.22.254.35 ./home/ubuntu/dicoding/deploy/simple-python-pyinstaller-app/deploy.sh'
                '''
                }
            }
        }
    } finally {
        archiveArtifacts 'dist/add2vals'
        sleep(time: 1, unit: 'MINUTES')
    }
}
